jellyfin:

  service:
    type: LoadBalancer

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
      - secretName: jellyfin-tls
        hosts:
          - jellyfin.bobby-dev.de
    hosts:
      - host: jellyfin.bobby-dev.de
        paths:
          - path: /
            pathType: Prefix

  persistence:
    config:
      storageClass: config
    media:
      existingClaim: jellyfin

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 2000
    runAsGroup: 2000