apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cert
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: CLOUDFLARE_CERT_API_TOKEN
      remoteRef:
        key: CLOUDFLARE_CERT_API_TOKEN
