apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: PROWLARR__AUTH__APIKEY
      remoteRef:
        key: PROWLARR__AUTH__APIKEY