apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: jellyfin