apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.155
    path: /mnt/nfs/data/media