apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth-credentials
            namespace: default
            key: clientId
          clientSecret:
            name: infisical-auth-credentials
            namespace: default
            key: clientSecret
      secretsScope:
        projectSlug: homlab-ow-u2
        environmentSlug: default
        secretsPath: /
        recursive: true
        expandSecretReferences: false
      hostAPI: https://eu.infisical.com