apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  target:
    name: argocd-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientSecret
      remoteRef:
        key: ARGOCD_OIDC_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None