apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
