app-template:
  controllers:
    netcup-dyndns:
      type: cronjob
      cronjob:
        timeZone: Europe/Berlin
        schedule: "*/30 * * * *"
      containers:
        app:
          image:
            repository: ghcr.io/marvin-steinke/netcup-dyndns-client
            tag: "5.0"
          env:
            DOMAINLIST: "bobby-dev.de: @, *"
            CHANGE_TTL: false
          envFrom:
            - secretRef:
                name: netcup
