apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: API_KEY
      remoteRef:
        key: JELLYSEERR_API_KEY