apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: RADARR__AUTH__APIKEY