app-template:
  controllers:
    cloudflare-ddns:
      type: cronjob
      cronjob:
        timeZone: Europe/Berlin
        schedule: "*/30 * * * *"
      containers:
        app:
          image:
            repository: docker.io/favonia/cloudflare-ddns
            tag: 1.15.1
          env:
            DOMAINS: bobby-dev.de
            PROXIED: true
            IP6_PROVIDER: none
          envFrom:
            - secretRef:
                name: cloudflare-ddns
