app-template:
  controllers:
    sonarr:
      containers:
        app:
          image:
            repository: ghcr.io/home-operations/sonarr
            tag: 4.0.14.2938
          env:
            SONARR__APP__INSTANCENAME: Sonarr
            SONARR__AUTH__METHOD: External
            SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
            SONARR__LOG__DBENABLED: "False"
            SONARR__LOG__LEVEL: info
            SONARR__SERVER__PORT: &port 8989
            SONARR__UPDATE__BRANCH: develop
          envFrom:
            - secretRef:
                name: sonarr
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

  service:
    app:
      controller: sonarr
      type: LoadBalancer
      ports:
        http:
          port: *port

  persistence:
    config:
      storageClass: config
      accessMode: ReadWriteOnce
      size: 5Gi
    add-ons:
      type: emptyDir
    tmp:
      type: emptyDir
    data:
      type: nfs
      server: 192.168.2.226
      path: /mnt/nfs/data