authentik:
  global:
    envFrom:
      - secretRef:
          name: authentik-external
  authentik:
    postgresql:
      host: 192.168.2.117
  server:
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: authentik-tls
          hosts:
            - authentik.bobby-dev.de
      hosts:
        - authentik.bobby-dev.de
