apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  target:
    name: argocd-oidc
  data:
    - secretKey: ARGOCD_OAUTH2_CLIENT_SECRET
      remoteRef:
        key: ARGOCD_OIDC_CLIENT_SECRET