apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_KEY
