apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: POSTGRESQL_USER
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: POSTGRESQL_PW
