apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mullvad
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: WIREGUARD_ADDRESSES