app-template:
  controllers:
    radarr:
      pod:
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000
          runAsNonRoot: true
          fsGroup: 2000
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        app:
          image:
            repository: ghcr.io/home-operations/radarr
            tag: 5.27.5.10184
          env:
            RADARR__APP__INSTANCENAME: Radarr
            RADARR__AUTH__METHOD: External
            RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
            RADARR__LOG__DBENABLED: "False"
            RADARR__LOG__LEVEL: info
            RADARR__SERVER__PORT: &port 7878
            RADARR__UPDATE__BRANCH: develop
          envFrom:
            - secretRef:
                name: radarr
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

  service:
    app:
      controller: radarr
      type: LoadBalancer
      ports:
        http:
          port: *port

  persistence:
    config:
      storageClass: config
      accessMode: ReadWriteOnce
      size: 5Gi
    add-ons:
      type: emptyDir
    tmp:
      type: emptyDir
    data:
      type: nfs
      server: 192.168.2.191
      path: /mnt/nfs/data