apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: SABNZBD__API_KEY
      remoteRef:
        key: SABNZBD__API_KEY
    - secretKey: SABNZBD__NZB_KEY
      remoteRef:
        key: SABNZBD__NZB_KEY