apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netcup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  refreshInterval: "0"
  data:
    - secretKey: APIKEY
      remoteRef:
        key: NETCUP_APIKEY
    - secretKey: CUSTOMERNR
      remoteRef:
        key: NETCUP_CUSTOMERNR
    - secretKey: APIPASSWORD
      remoteRef:
        key: NETCUP_APIPASSWORD
