app-template:
  controllers:
    sabnzbd:
      pod:
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000
          runAsNonRoot: true
          fsGroup: 2000
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        app:
          image:
            repository: ghcr.io/home-operations/sabnzbd
            tag: 4.5.3
          env:
            SABNZBD__PORT: &port 8585
            SABNZBD__HOST_WHITELIST_ENTRIES: >-
              sabnzbd,
              sabnzbd.downloads,
              sabnzbd.downloads.svc,
              sabnzbd.downloads.svc.cluster,
              sabnzbd.downloads.svc.cluster.local,
          envFrom:
            - secretRef:
                name: sabnzbd
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api?mode=version
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
            startup:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - sh
                    - -c
                    - if [ $(wget -q -O- https://ipinfo.io/country) == 'NL' ]; then exit 0; else exit $?; fi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

  service:
    app:
      controller: sabnzbd
      type: LoadBalancer
      ports:
        http:
          port: *port

  persistence:
    config:
      storageClass: config
      accessMode: ReadWriteOnce
      size: 5Gi
    tmp:
      type: emptyDir
    usenet:
      type: nfs
      server: 192.168.2.191
      path: /mnt/nfs/data
      globalMounts:
        - path: /data/usenet
          subPath: usenet