name: Renovate
run-name: Renovate - ${{ github.ref_name }} - ${{ github.run_number }}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.6
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
